### PR TITLE
Use `foundry-toolchain`

### PR DESCRIPTION
**Pull request by onbjerg**
Do not merge until the first nightly version is released :blush:

### CODE REVIEW

**Comment by onbjerg** [comment]
Good to merge now! https://github.com/gakonst/foundry/releases

Edit: Hold on.. testing this action myself and there is an issue :angry:

**Comment by onbjerg** [comment]
All good now! Just had to bundle the action :smile:

**Review by gakonst — APPROVED** [review]
Lgtm

**Comment by FrankieIsLost** [comment]
Insane speed-up GG

**Pull request merged**
